name: Data Visualization Journal
title: Data Visualization Journal
description: Journal for Fall 2021 MATC Honors Project
url: https://caseybrant.com/data-viz-journal/
baseurl: https://caseybrant.com/data-viz-journal/

markdown: kramdown
highlighter: rouge
